services:
  - type: web
    name: nearby_shops2_docker
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free 
    branch: master 
    dockerCommand: gunicorn nearby_shops2.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: nearbyshops_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromRedis:
          name: nearbyshops_redis
          property: connectionString

  - type: web
    name: nearby_shops2_celery
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free 
    branch: master 
    dockerCommand: celery --app nearby_shops2 worker --loglevel info --concurrency 4
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: nearbyshops_db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: nearbyshops_redis
          property: connectionString
