# Generated by Django 4.0 on 2023-02-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20230220_2146'),
    ]

    operations = [
    ]
