# Generated by Django 4.0 on 2023-03-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20230220_2356'),
    ]

    operations = [
    ]
